apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-whitelist
  namespace: test-nginx-server
spec:
  podSelector: {}
  policyTypes:
  - Egress
  ingress: []
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system