apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-whitelist
  namespace: test-nginx-server
spec:
  podSelector:
    matchLabels:
      app: nginx-server
  policyTypes:
  - Egress
  - Ingress
  ingress: []
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system