apiVersion: v1
kind: Namespace
metadata:
  name: test-ngnix-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  namespace: test-ngnix-server
  app: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: test-ngnix-server
spec:
  selector:
    app: nginx-server
  ports:
  - name: http
    port: 80
    targetPort: 80
